### ISSUE TITLE
How do I make the scrollview horizontal?

### ISSUE THREAD

**Issue by seohangyu** [yeyintkoko/infinite-scroll-react-native#1]
SOS..

**Comment by yeyintkoko** [comment]
I just uploaded a horizontal scroll support version to npm. You just need to add "horizontal" prop in the component property for horizontal scroll view.
Just <code>npm i infinite-scroll-x --save</code> and try again.

**Comment by seohangyu** [comment]
Thank you for your quick reply +_+!!
